name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b088fddb89f1839c21a78ee6e8cb5289da91ea5dcc81d7573f2ec5173d9df45d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
