name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4adf9f9a2758deca6b7495533b0aa6a1f485a390c501fd329b2b24175e1835f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
