name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8025582211aa1ab6487b45f61604528101c1009efbe7d09fa275eb695af74379"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
