name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fca640bcb8e6f0197f1fb40c356314d32c769d3368041475e26bf45a3cc510c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
