name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "492afab2e23ab60ab1957bf6122e6a5eb9746d614d9c188a84ec2c13295ee518"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
